name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
          #- macos-12
        dc:
          - dmd-2.109.1
          - dmd-2.099.1
          - ldc-1.40.0
          - ldc-1.29.0

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install ${{ matrix.dc }}
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}

      - name: "Posix: Run tests"
        if: runner.os != 'Windows'
        run: build/ci.sh
        env:
          TERM: xterm

      - name: "Windows: Run tests"
        if: runner.os == 'Windows'
        run: build\ci.bat

      - uses: codecov/codecov-action@v5.1.2
